version: '3.9'

services:
  # 1. The Database
  db:
    image: postgres:15-alpine
    container_name: workledger-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: workledger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - '5434:5432' # Kept on 5434 to completely avoid conflict with Gym DB (5433)
    volumes:
      - workledger-db-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M

  # 2. The Backend
  backend:
    build:
      context: ./WorkLedger_Backend
    container_name: workledger-backend
    restart: unless-stopped
    ports:
      - '8081:8080' # Exposed on 8081 so it doesn't conflict with Gym Backend (8080)
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/workledger
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 1G

  # 3. The Frontend
  frontend:
    build:
      context: ./WorkLedger_Frontend
    container_name: workledger-frontend
    restart: unless-stopped
    ports:
      - '5174:80' # Changed host port to 5174 so port 80 stays completely clear!
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  workledger-db-data: